# Changes here will be overwritten by Copier
_commit: 2dae20a
_src_path: gh:LSSTDESC/RAIL-project-template
author_email: later@later.com
author_name: LSST Dark Energy Science Collaboration (DESC)
create_example_module: false
package_name: sklearn
project_name: pz-rail-sklearn
